### ISSUE TITLE
RF doesnt work at Spigot Server 1.8.8

### ISSUE THREAD

**Issue by JarydX** [Olyol95/RecipeFinder#1]
When starting the server there is an error message:

org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: org/noip/olyol95/recipefinder/RecipeFinder : Unsupported major.minor version 52.0
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135) ~[craftbukkit.jar:git-Spigot-5f38d38-12698ea]
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:329) ~[craftbukkit.jar:git-Spigot-5f38d38-12698ea]
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
    at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:292) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
    at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:198) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [craftbukkit.jar:git-Spigot-5f38d38-12698ea]
    at java.lang.Thread.run(Unknown Source) [?:1.7.0_71]
Caused by: java.lang.UnsupportedClassVersionError: org/noip/olyol95/recipefinder/RecipeFinder : Unsupported major.minor version 52.0
    at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.7.0_71]
    at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.7.0_71]
    at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.7.0_71]
    at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.7.0_71]
    at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.7.0_71]
    at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_71]
    at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.7.0_71]
    at java.security.AccessController.doPrivileged(Native Method) ~[?:1.7.0_71]
    at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.7.0_71]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[craftbukkit.jar:git-Spigot-5f38d38-12698ea]
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[craftbukkit.jar:git-Spigot-5f38d38-12698ea]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_71]
    at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.7.0_71]
    at java.lang.Class.forName0(Native Method) ~[?:1.7.0_71]
    at java.lang.Class.forName(Unknown Source) ~[?:1.7.0_71]
    at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:64) ~[craftbukkit.jar:git-Spigot-5f38d38-12698ea]
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:131) ~[craftbukkit.jar:git-Spigot-5f38d38-12698ea]
    ... 6 more

Can you please fix it?

**Comment by Olyol95** [comment]
I think your problem could be related to your Java runtime version, as opposed to your version of Spigot. I have released an [updated version](https://github.com/Olyol95/RecipeFinder/releases/download/2.1.1/RecipeFinder.jar) which should work for all runtime versions greater than or equal to Java 6.

**Comment by JarydX** [comment]
Yep, thats it :) Used Java 8 instead, now it works perfectly. Thank you!

**Comment by Olyol95** [comment]
Great, no problem! :)
